[package]
name = "unixconn-rust"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.5.0"
uuid = { version = "1.10.0", features = ["v4"] }
